apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: config-service
  labels:
    app: config-service
spec:
  type: LoadBalancer
  selector:
    app: config-service
  ports:
    - port: 8080
      targetPort: 8080
